
const dataset = 
{
    "loading": false,
    "columns": [
        {
            "name": "fullname",
            "displayName": "Full Name",
            "dataType": "SingleLine.Text",
            "alias": "fullname",
            "order": 0,
            "visualSizeFactor": 200,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": true,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address1_composite",
            "displayName": "Address",
            "dataType": "Multiple",
            "alias": "address1_composite",
            "order": 1,
            "visualSizeFactor": 229,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address1_name",
            "displayName": "Address 1: Name",
            "dataType": "SingleLine.Text",
            "alias": "address1_name",
            "order": 2,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address1_postofficebox",
            "displayName": "Address 1: Post Office Box",
            "dataType": "SingleLine.Text",
            "alias": "address1_postofficebox",
            "order": 3,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address2_county",
            "displayName": "Address 2: County",
            "dataType": "SingleLine.Text",
            "alias": "address2_county",
            "order": 4,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address2_fax",
            "displayName": "Address 2: Fax",
            "dataType": "SingleLine.Text",
            "alias": "address2_fax",
            "order": 5,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address2_latitude",
            "displayName": "Address 2: Latitude",
            "dataType": "FP",
            "alias": "address2_latitude",
            "order": 6,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address2_longitude",
            "displayName": "Address 2: Longitude",
            "dataType": "FP",
            "alias": "address2_longitude",
            "order": 7,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address2_name",
            "displayName": "Address 2: Name",
            "dataType": "SingleLine.Text",
            "alias": "address2_name",
            "order": 8,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address2_postofficebox",
            "displayName": "Address 2: Post Office Box",
            "dataType": "SingleLine.Text",
            "alias": "address2_postofficebox",
            "order": 9,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address2_telephone2",
            "displayName": "Address 2: Telephone 2",
            "dataType": "SingleLine.Phone",
            "alias": "address2_telephone2",
            "order": 10,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address2_telephone1",
            "displayName": "Address 2: Telephone 1",
            "dataType": "SingleLine.Phone",
            "alias": "address2_telephone1",
            "order": 11,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "applicationid",
            "displayName": "Application ID",
            "dataType": "",
            "alias": "applicationid",
            "order": 12,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "businessunitid",
            "displayName": "Business Unit",
            "dataType": "Lookup.Simple",
            "alias": "businessunitid",
            "order": 13,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address1_city",
            "displayName": "City",
            "dataType": "SingleLine.Text",
            "alias": "address1_city",
            "order": 14,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "transactioncurrencyid",
            "displayName": "Currency",
            "dataType": "Lookup.Simple",
            "alias": "transactioncurrencyid",
            "order": 15,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "defaultodbfoldername",
            "displayName": "Default OneDrive for Business Folder Name",
            "dataType": "SingleLine.Text",
            "alias": "defaultodbfoldername",
            "order": 16,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "personalemailaddress",
            "displayName": "Email 2",
            "dataType": "SingleLine.Email",
            "alias": "personalemailaddress",
            "order": 17,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "employeeid",
            "displayName": "Employee",
            "dataType": "SingleLine.Text",
            "alias": "employeeid",
            "order": 18,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "exchangerate",
            "displayName": "Exchange Rate",
            "dataType": "Decimal",
            "alias": "exchangerate",
            "order": 19,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "jobtitle",
            "displayName": "Job Title",
            "dataType": "SingleLine.Text",
            "alias": "jobtitle",
            "order": 20,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "caltype",
            "displayName": "License Type",
            "dataType": "OptionSet",
            "alias": "caltype",
            "order": 21,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "defaultmailbox",
            "displayName": "Mailbox",
            "dataType": "Lookup.Simple",
            "alias": "defaultmailbox",
            "order": 22,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        },
        {
            "name": "address1_telephone1",
            "displayName": "Main Phone",
            "dataType": "SingleLine.Phone",
            "alias": "address1_telephone1",
            "order": 23,
            "visualSizeFactor": 100,
            "isHidden": false,
            "imageProviderWebresource": "",
            "imageProviderFunctionName": "",
            "isPrimary": false,
            "cellType": "",
            "disableSorting": false
        }
    ],
}

const allocatedWidth = 1385

it( 'dummy', () => {

    expect(true).toBeTruthy()
})