name: "create pcf"

on:
  workflow_dispatch:
    inputs:
     PCFName:
      description: 'PCF name'
      required: true
      #default: 'false'
jobs:
  create-pcf:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install Powerapps CLI
        run: |
            dotnet add package Microsoft.PowerApps.CLI --version 1.5.5
      # - name: install Powerapps CLI
      #   run: |
      #       msiexec /i powerapps-cli-1.0.msi /quiet /qn /norestart

      - name: Create PCF
        run: |
            echo "creating PCF named: ${{ github.event.inputs.PCFName }}"
            npm install -g yo
            npm install -g generator-pcf
            yo pcf --force --n ${{ github.event.inputs.PCFName }}
