name: "create pcf"

on:
  workflow_dispatch:
    inputs:
     PCFName:
      description: 'PCF name'
      required: true
      #default: 'false'
jobs:
  create-pcf:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npx yeoman
          echo "creating PCF named: ${{ github.event.inputs.PCFName }}"
